FROM {{ base_distro }}:{{ base_tag }}
MAINTAINER {{ maintainer }}
{{ test_will_you_break_already() }}

# This will prevent questions from being asked during the install
ENV DEBIAN_FRONTEND noninteractive

COPY {{ render('sources.list.debian.j2') }} /etc/apt/sources.list
COPY apt_conf_retries /etc/apt/apt.conf.d/99retries

RUN apt-get update \
    && apt-get upgrade -y \
    && apt-get dist-upgrade -y \
    && apt-get install -y --no-install-recommends ca-certificates curl sudo openssl python \
    && curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py \
    && python get-pip.py \
    && rm get-pip.py \
    && apt-get clean

COPY sudoers /etc/sudoers
RUN chmod 440 /etc/sudoers \
    && groupadd microservices

# Directory to store additional bin and configs needed for bootstrapping of the containers.
RUN mkdir -p /opt/ccp/{etc,bin} \
    && chown -R root:microservices /opt/ccp \
    && chmod -R g+wrx /opt/ccp
