FROM {{ namespace }}/base:{{ tag }}
MAINTAINER {{ maintainer }}

# This will prevent questions from being asked during the install
ENV DEBIAN_FRONTEND noninteractive

RUN apt-get install -y --no-install-recommends netcat lvm2 open-iscsi tgt vim less patch \
    && apt-get clean
